version: "2"
services:
  # 服务注册中心
  register-server:
    build: register-server
    image: springcloud-mall/register-server
    ports:
      - "8080:8080"
  # 用户相关服务
  service-user:
    build: service-user
    image: springcloud-mall/service-user
  # 商品相关服务
  service-goods:
    build: service-goods
    image: springcloud-mall/service-goods
  # 商品相关服务2 部署两个容器，实现负载均衡
  service-goods2:
    image: springcloud-mall/service-goods
  # 服务网关
  api-gateway:
    build: api-gateway
    image: springcloud-mall/api-gateway
    ports:
      - "8088:8080"
  # 监控
  app-monitor:
    build: app-monitor
    image: springcloud-mall/app-monitor
    ports:
      - "9000:8080"

