spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-server:8080/eureka/

zuul:
  routes:
    api-user:
      path: /api/user/**
      serviceId: service-user
    api-goods:
      path: /api/goods/**
      serviceId: service-goods
    api-test:
      path: /api/test/**
      serviceId: app-test

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
