spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-server:8080/eureka/

zuul:
  routes:
    api-a:
      path: /api/user/**
      serviceId: service-user
    api-b:
      path: /api/goods/**
      serviceId: service-goods
