spring:
  application:
    name: service-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-server:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

